function  status =  XuPMatrixVer1(s_date)

% s_date is 'YY-MM-DD'

mkdir(['data/' s_date '/calphan']);
mkdir(['data/' s_date '/air']);

mkdir('configs/temp_config/calphan');
XuModifyJsoncFile('configs/calphan/config_preprocessing.jsonc',...
    'RawDataPrjFolder',['./data/' s_date '/calphan/'],...
    'configs/temp_config/calphan/config_preprocessing.jsonc');
XuModifyJsoncFile('configs/temp_config/calphan/config_preprocessing.jsonc',...
    'RawDataBkgFolder',['./data/' s_date '/air/']);
XuModifyJsoncFile('configs/temp_config/calphan/config_preprocessing.jsonc',...
    'RawDataBkgName',['1_te.evi']);
XuModifyJsoncFile('configs/temp_config/calphan/config_preprocessing.jsonc',...
    'RawDataPrjName',['1_te.evi']);

XuModifyJsoncFile('configs/calphan/config_fbp.jsonc',...
    'InputDir',['./sgm/' s_date '/calphan'],...
    'configs/temp_config/calphan/config_fbp.jsonc');
XuModifyJsoncFile('configs/temp_config/calphan/config_fbp.jsonc',...
    'OutputDir',['./rec/' s_date '/calphan']);

XuModifyJsoncFile('configs/calphan/config_calc_pmatrix.jsonc',...
    'ReconCalPhanImage',['rec/' s_date '/calphan/rec_1_TE.raw'],...
    'configs/temp_config/calphan/config_calc_pmatrix.jsonc');
XuModifyJsoncFile('configs/temp_config/calphan/config_calc_pmatrix.jsonc',...
    'SinogramCalPhanName',['sgm/' s_date '/calphan/sgm_1_TE.raw']);

XuModifyJsoncFile('configs/calphan/config_one_stop_recon.jsonc',...
    'ConfigFolder','configs/temp_config/calphan',...
    'configs/temp_config/calphan/config_one_stop_recon.jsonc');

XuWholeReconProcessWithConfig('configs/temp_config/calphan/config_one_stop_recon.jsonc');
%%
Xu2DPmatrixFromCalPhantom_ver2('configs/temp_config/calphan/config_calc_pmatrix.jsonc',...
    'configs/temp_config/calphan/config_fbp.jsonc',s_date);
%%
% close all;
% XuModifyJsoncFile('configs/temp_config/calphan/config_calc_pmatrix.jsonc',...
%     'ReconCalPhanImage',['rec/' s_date '/calphan/measured_p_rec_1_te.raw']);
% 
% Xu2DPmatrixFromCalPhantom_ver2('configs/temp_config/calphan/config_calc_pmatrix.jsonc',...
%     'configs/temp_config/calphan/config_fbp.jsonc',s_date);

%%
status =1;